FROM node:20-slim

WORKDIR /app/frontend

COPY frontend/package.json frontend/pnpm-lock.yaml ./

RUN npm install --frozen-lockfile

COPY frontend/ .

RUN npm run build

EXPOSE $PORT

CMD ["npm", "start"]
